
name: Run Worker

description: Sets up a Redis Cluster instance needed to run the tests

inputs:
  launch_darkly_sdk_key:
    description: 'The Launch Darkly SDK key to use'
    required: false
    default: ''

runs:
  using: composite

  steps:
    - name: Build worker
      shell: bash
      run: CI='' pnpm build:worker

    - name: Start worker
      shell: bash
      env:
        LAUNCH_DARKLY_SDK_KEY: ${{ inputs.launch_darkly_sdk_key }}
      run: cd apps/worker && pnpm start:test &

    - name: Wait on worker
      shell: bash
      run: wait-on --timeout=180000 http://127.0.0.1:1342/v1/health-check
