name: Validate Swagger

description: Validates the swagger from the API

runs:
  using: composite

  steps:
    - name: Get swagger json as file
      shell: bash
      run: |
        curl -o swagger.json http://localhost:1336/api-json  

    - uses: char0n/swagger-editor-validate@v1
      with:
        definition-file: swagger.json

    - name: Kill port for api 1336 for unit tests
      shell: bash
      run: sudo kill -9 $(sudo lsof -t -i:1336)
