name: E2E API Tests

# Controls when the action will run. Triggers the workflow on push or pull request
on:
  workflow_call:

    inputs:
      ee:
        description: 'use the ee version of api'
        required: false
        default: false
        type: boolean
      submodules:
        description: 'The flag controlling whether we want submodules to checkout'
        required: false
        default: false
        type: boolean
      submodule_branch:
        description: 'Submodule branch to checkout to'
        required: false
        default: 'main'
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  e2e_api:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 80

    permissions:
      contents: read
      packages: write
      deployments: write
      id-token: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - id: setup
        run: |
          if ! [[ -z "${{ secrets.SUBMODULES_TOKEN }}" ]]; then
            echo "has_token=true" >> $GITHUB_OUTPUT
          else
            echo "has_token=false" >> $GITHUB_OUTPUT
          fi
      - uses: actions/checkout@v3
      # checkout with submodules if token is provided
      - uses: ./.github/actions/setup-project
      - uses: ./.github/actions/setup-redis-cluster
      - uses: mansagroup/nrwl-nx-action@v3
        with:
          targets: lint
          projects: "@novu/api"

      - uses: ./.github/actions/start-localstack

      - uses: ./.github/actions/run-worker
        with:
          launch_darkly_sdk_key: ${{ secrets.LAUNCH_DARKLY_SDK_KEY }}

        # Runs a single command using the runners shell
      - name: Build API
        run: CI='' pnpm build:api

      - name: Run E2E tests
        env:
          LAUNCH_DARKLY_SDK_KEY: ${{ secrets.LAUNCH_DARKLY_SDK_KEY }}
        run: |
          cd apps/api && pnpm test:e2e

      - name: Kill port for worker 1342 for unit tests
        run: sudo kill -9 $(sudo lsof -t -i:1342)

      - name: Run unit tests
        run: |
          cd apps/api && pnpm test
          
  
